### ISSUE TITLE
Newer versions?

### ISSUE THREAD

**Issue by LKD-PIX** [CrossVas/CrossFarming#4]
I am specifically looking for 1.20.1, are you interested in porting it to this in the future?

**Comment by CrossVas** [comment]
The mod is currently on hold. No new version will be provided, but I do plan to revive it in the future. No ETAs, sorry.

To give a little more information.
This mod was made as an experiment for me to try and learn block entities with some more complex logic.
The result is somehow working, but I'm sure this could be improved. For that I need more time and I don't want to just blindly port `maybe` a broken code to new versions.
Once I feel like doing it, I'll update the mod.

Meanwhile you can try: https://www.curseforge.com/minecraft/mc-mods/farmingutils
Sorry.
